package net.sashakyotoz.unseenworld.registries;

import net.minecraft.ChatFormatting;
import net.sashakyotoz.unseenworld.UnseenWorldMod;
import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.event.BuildCreativeModeTabContentsEvent;

import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.network.chat.Component;
import net.minecraft.core.registries.Registries;

@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD)
public class UnseenWorldTabs {
	public static final DeferredRegister<CreativeModeTab> REGISTRY = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, UnseenWorldMod.MODID);
	public static final RegistryObject<CreativeModeTab> UNSEEN_WORLD_TOOLS = REGISTRY.register("unseen_world_tools",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.unseen_world.unseen_world_tools")).icon(() -> new ItemStack(UnseenWorldItems.VOID_INGOT_PICKAXE.get())).displayItems((parameters, tabData) -> {
				tabData.accept(UnseenWorldItems.DEEP_GEM_PICKAXE.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_AXE.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_SHOVEL.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_HOE.get());
				tabData.accept(UnseenWorldItems.VOID_INGOT_PICKAXE.get());
				tabData.accept(UnseenWorldItems.VOID_INGOT_AXE.get());
				tabData.accept(UnseenWorldItems.VOID_INGOT_SHOVEL.get());
				tabData.accept(UnseenWorldItems.VOID_INGOT_HOE.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_PICKAXE.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_AXE.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_SHOVEL.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_HOE.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_PICKAXE.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_AXE.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_SHOVEL.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_HOE.get());
				tabData.accept(UnseenWorldItems.UNSEEN_PICKAXE.get());
				tabData.accept(UnseenWorldItems.UNSEEN_AXE.get());
				tabData.accept(UnseenWorldItems.UNSEEN_SHOVEL.get());
				tabData.accept(UnseenWorldItems.UNSEEN_HOE.get());
				tabData.accept(UnseenWorldItems.VOID_UPGRADE_SMITHING_TEMPLATE.get());
				tabData.accept(UnseenWorldItems.THE_DARKNESS.get());
				tabData.accept(UnseenWorldItems.DARK_GOLEM_HEART.get());
				tabData.accept(UnseenWorldItems.DARK_PEARL.get());
				tabData.accept(UnseenWorldItems.FIRE_PEARL.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM.get());
				tabData.accept(UnseenWorldBlocks.DEEP_GEM_ORE.get().asItem());
				tabData.accept(UnseenWorldBlocks.DEEP_GEM_BLOCK.get().asItem());
				tabData.accept(UnseenWorldItems.BLUE_VOID.get());
				tabData.accept(UnseenWorldItems.VOID_INGOT.get());
				tabData.accept(UnseenWorldBlocks.VOID_INGOT_ORE.get().asItem());
				tabData.accept(UnseenWorldBlocks.VOID_INGOT_BLOCK.get().asItem());
				tabData.accept(UnseenWorldItems.RAW_RED_TITANIUM.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_INGOT.get());
				tabData.accept(UnseenWorldBlocks.RED_TITANIUM_ORE.get().asItem());
				tabData.accept(UnseenWorldBlocks.RED_TITANIUM_BLOCK.get().asItem());
				tabData.accept(UnseenWorldItems.RAW_UNSEENIUM.get());
				tabData.accept(UnseenWorldItems.UNSEEN_INGOT.get());
				tabData.accept(UnseenWorldBlocks.UNSEEN_ORE.get().asItem());
				tabData.accept(UnseenWorldBlocks.UNSEEN_BLOCK.get().asItem());
				tabData.accept(UnseenWorldItems.NATURERIUM_INGOT.get());
				tabData.accept(UnseenWorldBlocks.NATURERIUM_BLOCK.get().asItem());
				tabData.accept(UnseenWorldItems.RED_BLAZE_ROD.get());
				tabData.accept(UnseenWorldItems.BLAZE_SHIELD_SHARD.get());
				tabData.accept(UnseenWorldItems.TANZANITE_SHARD.get());
				tabData.accept(UnseenWorldItems.CHLORITE_SLATE_STONE_SHARD.get());
				tabData.accept(UnseenWorldItems.TEALIVE_STONY_SHARD.get());
				tabData.accept(UnseenWorldItems.DARK_FREE_SOUL.get());
				tabData.accept(UnseenWorldItems.DARK_WATER_BUCKET.get());
				tabData.accept(UnseenWorldItems.LIQUID_OF_CHIMERY_BUCKET.get());
			}).build());
	public static final RegistryObject<CreativeModeTab> UNSEEN_WORLD_COMBAT = REGISTRY.register("unseen_world_combat",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.unseen_world.unseen_world_combat").withStyle(ChatFormatting.DARK_RED)).icon(() -> new ItemStack(UnseenWorldItems.RED_TITANIUM_SWORD.get())).displayItems((parameters, tabData) -> {
				tabData.accept(UnseenWorldItems.DEEP_GEM_SWORD.get());
				tabData.accept(UnseenWorldItems.VOID_INGOT_SWORD.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_SWORD.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_POISONOUS_SWORD.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_SWORD.get());
				tabData.accept(UnseenWorldItems.UNSEEN_SWORD.get());
				tabData.accept(UnseenWorldItems.VOID_ENDERMAN_SWORD.get());
				tabData.accept(UnseenWorldItems.HEAVY_CLAYMORE.get());
				tabData.accept(UnseenWorldItems.LIGHT_TULVAR.get());
				tabData.accept(UnseenWorldItems.BLASTING_LANCER.get());
				tabData.accept(UnseenWorldItems.FIERY_SABER.get());
				tabData.accept(UnseenWorldItems.VOID_HAMMER.get());
				tabData.accept(UnseenWorldItems.REDNESS_HAMMER.get());
				tabData.accept(UnseenWorldItems.AMETHYST_HAMMER.get());
				tabData.accept(UnseenWorldItems.TEALIVY_VOID_SPEAR.get());
				tabData.accept(UnseenWorldItems.UNSEEN_TITANIUM_SPEAR.get());
				tabData.accept(UnseenWorldItems.NETHERIUM_STAFF.get());
				tabData.accept(UnseenWorldItems.VOID_STAFF.get());
				tabData.accept(UnseenWorldItems.TANZANITE_STAFF.get());
				tabData.accept(UnseenWorldItems.TEALIVY_FIRE_STAFF.get());
				tabData.accept(UnseenWorldItems.VOID_BOW.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_ARMOR_HELMET.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_ARMOR_CHESTPLATE.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_ARMOR_LEGGINGS.get());
				tabData.accept(UnseenWorldItems.DEEP_GEM_ARMOR_BOOTS.get());
				tabData.accept(UnseenWorldItems.VOIDINGOT_ARMOR_HELMET.get());
				tabData.accept(UnseenWorldItems.VOIDINGOT_ARMOR_CHESTPLATE.get());
				tabData.accept(UnseenWorldItems.VOIDINGOT_ARMOR_LEGGINGS.get());
				tabData.accept(UnseenWorldItems.VOIDINGOT_ARMOR_BOOTS.get());
				tabData.accept(UnseenWorldItems.UNSEEN_ARMOR_HELMET.get());
				tabData.accept(UnseenWorldItems.UNSEEN_ARMOR_CHESTPLATE.get());
				tabData.accept(UnseenWorldItems.UNSEEN_ARMOR_LEGGINGS.get());
				tabData.accept(UnseenWorldItems.UNSEEN_ARMOR_BOOTS.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_ARMOR_HELMET.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_ARMOR_CHESTPLATE.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_ARMOR_LEGGINGS.get());
				tabData.accept(UnseenWorldItems.RED_TITANIUM_ARMOR_BOOTS.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_ARMOR_HELMET.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_ARMOR_CHESTPLATE.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_ARMOR_LEGGINGS.get());
				tabData.accept(UnseenWorldItems.NATURERIUM_ARMOR_BOOTS.get());
				tabData.accept(UnseenWorldItems.KNIGHT_ARMOR_HELMET.get());
				tabData.accept(UnseenWorldItems.KNIGHT_ARMOR_CHESTPLATE.get());
				tabData.accept(UnseenWorldItems.KNIGHT_ARMOR_LEGGINGS.get());
				tabData.accept(UnseenWorldItems.KNIGHT_ARMOR_BOOTS.get());
				tabData.accept(UnseenWorldItems.BLAZER_HELMET.get());
				tabData.accept(UnseenWorldItems.BLAZER_SHIELD.get());
				tabData.accept(UnseenWorldItems.DARK_SKELETON_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.AMETHYST_GOLEM_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.DARK_PHANTOM_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.DUSTY_PINK_MAXOR_FISH_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.MOONFISH_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.CAVERN_SCARECROW_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.SAVAGE_SMALL_BLAZE_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.CHIMERIC_PURPLEMARER_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.CHIMERIC_REDMARER_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.NETHERMEN_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.RED_SLYLF_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.RED_BLAZE_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.STREDER_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.GHAST_OF_TEALIVE_VALLEY_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.TANZANITE_GUARDIAN_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.DARK_SPIRIT_WOLF_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.SNOWDRIFTER_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.VOID_ENDERMEN_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.TEALIVE_SKELETON_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.RED_RAVENGER_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.DARK_HOGLIN_SPAWN_EGG.get());
				tabData.accept(UnseenWorldItems.MOON_FISHIN_BUCKET.get());
				tabData.accept(UnseenWorldItems.DUSTY_PINK_MAXOR_FISH_BUCKET.get());
			}).build());
	public static final RegistryObject<CreativeModeTab> UNSEEN_WORLD_BLOCKS = REGISTRY.register("unseen_world_blocks",
			() -> CreativeModeTab.builder().title(Component.translatable("item_group.unseen_world.unseen_world_blocks")).icon(() -> new ItemStack(UnseenWorldBlocks.COLD_DARK_BRICKS.get())).displayItems((parameters, tabData) -> {
				tabData.accept(UnseenWorldBlocks.COLD_DARK_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRASS_BLOCK_OF_SHINY_REDLIGHT.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_GRASS_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_GRASS_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVE_LUMINOUS_GRASS_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.RED_OOZE.get().asItem());
				tabData.accept(UnseenWorldBlocks.CRYSTALLIZED_DARK_SAND.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_LEAVES.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_WOOD.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_LOG.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_PLANKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_FENCE.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_FENCE_GATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_DOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_TRAPDOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_PRESSURE_PLATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_BUTTON.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_LEAVES.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_WOOD.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_LOG.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_PLANKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_FENCE.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_FENCE_GATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_DOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_TRAPDOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_PRESSURE_PLATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_BUTTON.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_LIGHT_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_LEAVES.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_WOOD.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_LOG.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_PLANKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_FENCE.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_FENCE_GATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_DOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_TRAPDOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_PRESSURE_PLATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_BUTTON.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_LEAVES.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_WOOD.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_LOG.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_PLANKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_FENCE.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_FENCE_GATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_DOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_TRAPDOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_PRESSURE_PLATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_BUTTON.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_LEAVES.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_LOG.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_PLANKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_FENCE.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_FENCE_GATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_DOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_TRAPDOOR.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_PRESSURE_PLATE.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLY_WOOD_BUTTON.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZASHROOM_LIGHT.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_BLOCK_BUDDING.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_CLUSTER.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_BRICKS_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_BRICKS_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZANITE_BRICKS_WALL.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARKNESS_ANCIENT_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARKNESS_ANCIENT_BRICKS_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARKNESS_ANCIENT_BRICKS_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARKNESS_ANCIENT_BRICKS_WALL.get().asItem());
				tabData.accept(UnseenWorldBlocks.RED_DEEPSLATE_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.RED_DEEPSLATE_BRICKS_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.RED_DEEPSLATE_BRICKS_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.RED_DEEPSLATE_BRICKS_WALL.get().asItem());
				tabData.accept(UnseenWorldBlocks.CHLORITE_SLATE_STONE.get().asItem());
				tabData.accept(UnseenWorldBlocks.CHLORITE_SLATE_STONE_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.CHLORITE_SLATE_STONE_BRICKS_STAIRS.get().asItem());
				tabData.accept(UnseenWorldBlocks.CHLORITE_SLATE_STONE_BRICKS_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.CHLORITE_SLATE_STONE_BRICKS_WALL.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CURRANTSLATE.get());
				tabData.accept(UnseenWorldBlocks.DARK_CURRANTSLATE_STAIRS.get());
				tabData.accept(UnseenWorldBlocks.DARK_CURRANTSLATE_SLAB.get());
				tabData.accept(UnseenWorldBlocks.DARK_CURRANTSLATE_WALL.get());
				tabData.accept(UnseenWorldBlocks.REINFORCED_POLISHED_BLACKSTONE_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.REINFORCED_POLISHED_BLACKSTONE_BRICKS_SLAB.get().asItem());
				tabData.accept(UnseenWorldBlocks.ANCIENT_TRANSIENT_BLOCK_CLOSE.get().asItem());
				tabData.accept(UnseenWorldBlocks.REINFORCED_RED_ANCIENT_BRICKS.get().asItem());
				tabData.accept(UnseenWorldBlocks.BEACON_RUNE.get().asItem());
				tabData.accept(UnseenWorldBlocks.BEACON_OF_WEAPONS.get().asItem());
				tabData.accept(UnseenWorldBlocks.DRIPSTONE_OF_AMETHYST_OVERGROWTH.get().asItem());
				tabData.accept(UnseenWorldBlocks.DEEP_WATER_ANFELTSIA.get().asItem());
				tabData.accept(UnseenWorldBlocks.CRIMSERRY_SOUL_CROP.get().asItem());
				tabData.accept(UnseenWorldBlocks.MISTERY_CROP_FLOWER.get().asItem());
				tabData.accept(UnseenWorldBlocks.NIGHTDEW_OF_CHIMERIC_DARKNESS.get().asItem());
				tabData.accept(UnseenWorldBlocks.OUT_GROWT_APPLE_BUSH.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_FLOWING_AZALEA.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_AZALEA.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_VINE_FLOWER.get().asItem());
				tabData.accept(UnseenWorldBlocks.LUMINOUS_AMETHYST_VINE.get().asItem());
				tabData.accept(UnseenWorldBlocks.DARK_CRIMSON_SAPLING.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_TREE_SAPLING.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_TREE_SAPLING.get().asItem());
				tabData.accept(UnseenWorldBlocks.GREENISH_BURLYWOOD_SAPLING.get().asItem());
				tabData.accept(UnseenWorldBlocks.GRIZZLY_SAPLING.get().asItem());
				tabData.accept(UnseenWorldBlocks.WILD_CRIMSERRY_SOUL_FLOWER.get().asItem());
				tabData.accept(UnseenWorldBlocks.AMETHYST_GRASS.get().asItem());
				tabData.accept(UnseenWorldBlocks.GLOWORCHID.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_PLUMERIA.get().asItem());
				tabData.accept(UnseenWorldBlocks.TEALIVY_JADE_VINE_FLOWER.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZASHROOM.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZASHROOM_BLOCK.get().asItem());
				tabData.accept(UnseenWorldBlocks.TANZASHROOM_STEM.get().asItem());
			}).build());

	@SubscribeEvent
	public static void buildTabContentsVanilla(BuildCreativeModeTabContentsEvent tabData) {
		if (tabData.getTabKey() == CreativeModeTabs.TOOLS_AND_UTILITIES) {
			tabData.accept(UnseenWorldItems.MUSIC_DISC_PIANO.get());
			tabData.accept(UnseenWorldItems.MUSIC_DISC_HAPPY_PLACE.get());
		}
		if (tabData.getTabKey() == CreativeModeTabs.FOOD_AND_DRINKS) {
			tabData.accept(UnseenWorldItems.OUTGROWTH_APPLE.get());
			tabData.accept(UnseenWorldItems.CHIMERIC_BLUE_PEPPER.get());
			tabData.accept(UnseenWorldItems.PURPLE_BERRIES.get());
			tabData.accept(UnseenWorldItems.LUMINOUS_PORKCHOP.get());
			tabData.accept(UnseenWorldItems.LUMINOUS_COOKED_PORKCHOP.get());
			tabData.accept(UnseenWorldItems.BERRIES_OF_BLOOMING_VINE.get());
			tabData.accept(UnseenWorldItems.CRIMSERRY_SOUL_BERRY.get());
			tabData.accept(UnseenWorldItems.DISHWITH_BERRIES.get());
			tabData.accept(UnseenWorldItems.BOWL_WITH_BERRIES_WITHOUT_EFFECT.get());
			tabData.accept(UnseenWorldItems.MOON_FISH_FOOD.get());
			tabData.accept(UnseenWorldItems.COOKED_MOON_FISH.get());
			tabData.accept(UnseenWorldItems.NIGHTDEW_NECTAR_BOTTLE.get());
			tabData.accept(UnseenWorldItems.DUSTY_PINK_MAXOR_FISH_FOOD.get());
			tabData.accept(UnseenWorldItems.COOKED_DUSTY_PINK_MAXOR_FISH.get());
			tabData.accept(UnseenWorldItems.DISH_VEGETABLE_WITH_PORK.get());
		}
	}
}
