
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.sashakyotoz.unseenworld.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.fml.common.Mod;
import net.minecraftforge.eventbus.api.SubscribeEvent;
import net.minecraftforge.client.event.RegisterColorHandlersEvent;
import net.minecraftforge.api.distmarker.Dist;

import net.minecraft.world.level.block.Block;

import net.sashakyotoz.unseenworld.block.Void_ingotOreBlock;
import net.sashakyotoz.unseenworld.block.Void_ingotBlockBlock;
import net.sashakyotoz.unseenworld.block.UnseenOreBlock;
import net.sashakyotoz.unseenworld.block.UnseenBlockBlock;
import net.sashakyotoz.unseenworld.block.UndeadWarriorOfTheChimericDarknessBlock;
import net.sashakyotoz.unseenworld.block.TotemofGuddyBlazeBlock;
import net.sashakyotoz.unseenworld.block.TheWitherKnightBlockBlock;
import net.sashakyotoz.unseenworld.block.TheDarknessPortalBlock;
import net.sashakyotoz.unseenworld.block.TealivyWoodBlock;
import net.sashakyotoz.unseenworld.block.TealivyTreeSaplingBlock;
import net.sashakyotoz.unseenworld.block.TealivyTrapdoorBlock;
import net.sashakyotoz.unseenworld.block.TealivyStairsBlock;
import net.sashakyotoz.unseenworld.block.TealivySlabBlock;
import net.sashakyotoz.unseenworld.block.TealivyPressurePlateBlock;
import net.sashakyotoz.unseenworld.block.TealivyPlumeriaBlock;
import net.sashakyotoz.unseenworld.block.TealivyPlanksBlock;
import net.sashakyotoz.unseenworld.block.TealivyLogBlock;
import net.sashakyotoz.unseenworld.block.TealivyLeavesBlock;
import net.sashakyotoz.unseenworld.block.TealivyJadeVineFlowerBlock;
import net.sashakyotoz.unseenworld.block.TealivyFenceGateBlock;
import net.sashakyotoz.unseenworld.block.TealivyFenceBlock;
import net.sashakyotoz.unseenworld.block.TealivyDoorBlock;
import net.sashakyotoz.unseenworld.block.TealivyButtonBlock;
import net.sashakyotoz.unseenworld.block.TealiveLuminousGrassBlockBlock;
import net.sashakyotoz.unseenworld.block.TanzashroomStemBlock;
import net.sashakyotoz.unseenworld.block.TanzashroomLightBlock;
import net.sashakyotoz.unseenworld.block.TanzashroomBlockBlock;
import net.sashakyotoz.unseenworld.block.TanzashroomBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteClusterBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteBricksWallBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteBricksStairsBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteBricksSlabBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteBricksBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteBlockBuddingBlock;
import net.sashakyotoz.unseenworld.block.TanzaniteBlockBlock;
import net.sashakyotoz.unseenworld.block.SmallCrimserrySoulBerryBlock;
import net.sashakyotoz.unseenworld.block.ReinforcedRedAnientBricksBlock;
import net.sashakyotoz.unseenworld.block.ReinforcedPolishedBlackstoneBricksSlabBlock;
import net.sashakyotoz.unseenworld.block.ReinforcedPolishedBlackstoneBricksBlock;
import net.sashakyotoz.unseenworld.block.ReddeepslatebricksstairsBlock;
import net.sashakyotoz.unseenworld.block.ReddeepslatebricksslabBlock;
import net.sashakyotoz.unseenworld.block.ReddeepslatebricksFenceBlock;
import net.sashakyotoz.unseenworld.block.ReddeepslatebricksBlock;
import net.sashakyotoz.unseenworld.block.Red_TitaniumOreBlock;
import net.sashakyotoz.unseenworld.block.Red_TitaniumBlockBlock;
import net.sashakyotoz.unseenworld.block.RedOozeBlock;
import net.sashakyotoz.unseenworld.block.OutGrowtAppleBushBlock;
import net.sashakyotoz.unseenworld.block.NightdewOfChimericDarknessBlock;
import net.sashakyotoz.unseenworld.block.NatureriumBlockBlock;
import net.sashakyotoz.unseenworld.block.MisteryflowerWithFewBerriesBlock;
import net.sashakyotoz.unseenworld.block.MisteryflowerSaplingBlock;
import net.sashakyotoz.unseenworld.block.MisteryflowerBerriesBlock;
import net.sashakyotoz.unseenworld.block.LuminousamethystvineBlock;
import net.sashakyotoz.unseenworld.block.LiquidOfChimeryBlock;
import net.sashakyotoz.unseenworld.block.GrownCrimserrySoulBerryBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyWoodBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyTrapdoorBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyStairsBlock;
import net.sashakyotoz.unseenworld.block.GrizzlySlabBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyPressurePlateBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyPlanksBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyLogBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyLightBlockBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyLeavesBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyFenceGateBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyFenceBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyDoorBlock;
import net.sashakyotoz.unseenworld.block.GrizzlyButtonBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodWoodBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodStairsBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodSlabBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodPressurePlateBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodPlanksBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodLogBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodLeavesBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodFenceGateBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodFenceBlock;
import net.sashakyotoz.unseenworld.block.Greenish_BurlyWoodButtonBlock;
import net.sashakyotoz.unseenworld.block.GreenishBurlywoodSaplingBlock;
import net.sashakyotoz.unseenworld.block.GreenishBurlyWoodTrapdoorBlock;
import net.sashakyotoz.unseenworld.block.GreenishBurlyWoodDoorBlock;
import net.sashakyotoz.unseenworld.block.GrassBlockOfShinyRedlightBlock;
import net.sashakyotoz.unseenworld.block.GoldenchestBlock;
import net.sashakyotoz.unseenworld.block.DripstoneOfAmethystOvergrowthBlock;
import net.sashakyotoz.unseenworld.block.Deep_GemOreBlock;
import net.sashakyotoz.unseenworld.block.Deep_GemBlockBlock;
import net.sashakyotoz.unseenworld.block.DeepWaterAnfeltsiaBlock;
import net.sashakyotoz.unseenworld.block.DarkcrimsonsaplingBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonWoodBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonStairsBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonSlabBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonPressurePlateBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonPlanksBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonLogBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonLeavesBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonFenceGateBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonFenceBlock;
import net.sashakyotoz.unseenworld.block.Dark_crimsonButtonBlock;
import net.sashakyotoz.unseenworld.block.DarkWaterBlock;
import net.sashakyotoz.unseenworld.block.DarkGrassBlock;
import net.sashakyotoz.unseenworld.block.DarkCrimsonVineFlowerBlock;
import net.sashakyotoz.unseenworld.block.DarkCrimsonTrapdoorBlock;
import net.sashakyotoz.unseenworld.block.DarkCrimsonFlowingAzaliaBlock;
import net.sashakyotoz.unseenworld.block.DarkCrimsonDoorBlock;
import net.sashakyotoz.unseenworld.block.DarkCrimsonBloomingVineBlock;
import net.sashakyotoz.unseenworld.block.DarkCrimsonAzaleaBlock;
import net.sashakyotoz.unseenworld.block.DaknessAncientBricksWallBlock;
import net.sashakyotoz.unseenworld.block.DaknessAncientBricksStairsBlock;
import net.sashakyotoz.unseenworld.block.DaknessAncientBricksSlabBlock;
import net.sashakyotoz.unseenworld.block.DaknessAncientBricksBlock;
import net.sashakyotoz.unseenworld.block.CrystallizedDarkSandBlock;
import net.sashakyotoz.unseenworld.block.ColdDarkBricksBlock;
import net.sashakyotoz.unseenworld.block.ChloriteSlateStoneBricksWallBlock;
import net.sashakyotoz.unseenworld.block.ChloriteSlateStoneBricksStairsBlock;
import net.sashakyotoz.unseenworld.block.ChloriteSlateStoneBricksSlabBlock;
import net.sashakyotoz.unseenworld.block.ChloriteSlateStoneBricksBlock;
import net.sashakyotoz.unseenworld.block.ChloriteSlateStoneBlock;
import net.sashakyotoz.unseenworld.block.BlazerSummonBlockBlock;
import net.sashakyotoz.unseenworld.block.BeaconRuneBlock;
import net.sashakyotoz.unseenworld.block.BeaconOfWeaponsBlock;
import net.sashakyotoz.unseenworld.block.AncientTransientBlockOpenBlock;
import net.sashakyotoz.unseenworld.block.AncientTransientBlockCloseBlock;
import net.sashakyotoz.unseenworld.block.AmethystWoodBlock;
import net.sashakyotoz.unseenworld.block.AmethystTreeSaplingBlock;
import net.sashakyotoz.unseenworld.block.AmethystTrapdoorBlock;
import net.sashakyotoz.unseenworld.block.AmethystStairsBlock;
import net.sashakyotoz.unseenworld.block.AmethystSlabBlock;
import net.sashakyotoz.unseenworld.block.AmethystPressurePlateBlock;
import net.sashakyotoz.unseenworld.block.AmethystPlanksBlock;
import net.sashakyotoz.unseenworld.block.AmethystLogBlock;
import net.sashakyotoz.unseenworld.block.AmethystLeavesBlock;
import net.sashakyotoz.unseenworld.block.AmethystGrassBlockBlock;
import net.sashakyotoz.unseenworld.block.AmethystGrassBlock;
import net.sashakyotoz.unseenworld.block.AmethystFenceGateBlock;
import net.sashakyotoz.unseenworld.block.AmethystFenceBlock;
import net.sashakyotoz.unseenworld.block.AmethystDoorBlock;
import net.sashakyotoz.unseenworld.block.AmethystButtonBlock;
import net.sashakyotoz.unseenworld.UnseenWorldMod;

public class UnseenWorldModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, UnseenWorldMod.MODID);
	public static final RegistryObject<Block> SMALL_CRIMSERRY_SOUL_BERRY = REGISTRY.register("small_crimserry_soul_berry", () -> new SmallCrimserrySoulBerryBlock());
	public static final RegistryObject<Block> MISTERYFLOWER_SAPLING = REGISTRY.register("misteryflower_sapling", () -> new MisteryflowerSaplingBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_FENCE = REGISTRY.register("dark_crimson_fence", () -> new Dark_crimsonFenceBlock());
	public static final RegistryObject<Block> GRIZZLY_FENCE = REGISTRY.register("grizzly_fence", () -> new GrizzlyFenceBlock());
	public static final RegistryObject<Block> AMETHYST_FENCE = REGISTRY.register("amethyst_fence", () -> new AmethystFenceBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_FENCE = REGISTRY.register("greenish_burly_wood_fence", () -> new Greenish_BurlyWoodFenceBlock());
	public static final RegistryObject<Block> TEALIVY_FENCE = REGISTRY.register("tealivy_fence", () -> new TealivyFenceBlock());
	public static final RegistryObject<Block> NIGHTDEW_OF_CHIMERIC_DARKNESS = REGISTRY.register("nightdew_of_chimeric_darkness", () -> new NightdewOfChimericDarknessBlock());
	public static final RegistryObject<Block> OUT_GROWT_APPLE_BUSH = REGISTRY.register("out_growt_apple_bush", () -> new OutGrowtAppleBushBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_FLOWING_AZALIA = REGISTRY.register("dark_crimson_flowing_azalia", () -> new DarkCrimsonFlowingAzaliaBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_AZALEA = REGISTRY.register("dark_crimson_azalea", () -> new DarkCrimsonAzaleaBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_VINE_FLOWER = REGISTRY.register("dark_crimson_vine_flower", () -> new DarkCrimsonVineFlowerBlock());
	public static final RegistryObject<Block> LUMINOUSAMETHYSTVINE = REGISTRY.register("luminousamethystvine", LuminousamethystvineBlock::new);
	public static final RegistryObject<Block> DARKCRIMSONSAPLING = REGISTRY.register("darkcrimsonsapling", () -> new DarkcrimsonsaplingBlock());
	public static final RegistryObject<Block> AMETHYST_TREE_SAPLING = REGISTRY.register("amethyst_tree_sapling", () -> new AmethystTreeSaplingBlock());
	public static final RegistryObject<Block> TEALIVY_TREE_SAPLING = REGISTRY.register("tealivy_tree_sapling", () -> new TealivyTreeSaplingBlock());
	public static final RegistryObject<Block> GREENISH_BURLYWOOD_SAPLING = REGISTRY.register("greenish_burlywood_sapling", () -> new GreenishBurlywoodSaplingBlock());
	public static final RegistryObject<Block> GROWN_CRIMSERRY_SOUL_BERRY = REGISTRY.register("grown_crimserry_soul_berry", () -> new GrownCrimserrySoulBerryBlock());
	public static final RegistryObject<Block> AMETHYST_GRASS = REGISTRY.register("amethyst_grass", () -> new AmethystGrassBlock());
	public static final RegistryObject<Block> TEALIVY_PLUMERIA = REGISTRY.register("tealivy_plumeria", () -> new TealivyPlumeriaBlock());
	public static final RegistryObject<Block> TEALIVY_JADE_VINE_FLOWER = REGISTRY.register("tealivy_jade_vine_flower", () -> new TealivyJadeVineFlowerBlock());
	public static final RegistryObject<Block> TANZASHROOM = REGISTRY.register("tanzashroom", () -> new TanzashroomBlock());
	public static final RegistryObject<Block> TANZASHROOM_BLOCK = REGISTRY.register("tanzashroom_block", () -> new TanzashroomBlockBlock());
	public static final RegistryObject<Block> TANZASHROOM_STEM = REGISTRY.register("tanzashroom_stem", () -> new TanzashroomStemBlock());
	public static final RegistryObject<Block> DARK_WATER = REGISTRY.register("dark_water", () -> new DarkWaterBlock());
	public static final RegistryObject<Block> LIQUID_OF_CHIMERY = REGISTRY.register("liquid_of_chimery", () -> new LiquidOfChimeryBlock());
	public static final RegistryObject<Block> THE_DARKNESS_PORTAL = REGISTRY.register("the_darkness_portal", () -> new TheDarknessPortalBlock());
	public static final RegistryObject<Block> DEEP_GEM_ORE = REGISTRY.register("deep_gem_ore", () -> new Deep_GemOreBlock());
	public static final RegistryObject<Block> DEEP_GEM_BLOCK = REGISTRY.register("deep_gem_block", () -> new Deep_GemBlockBlock());
	public static final RegistryObject<Block> VOID_INGOT_ORE = REGISTRY.register("void_ingot_ore", () -> new Void_ingotOreBlock());
	public static final RegistryObject<Block> VOID_INGOT_BLOCK = REGISTRY.register("void_ingot_block", () -> new Void_ingotBlockBlock());
	public static final RegistryObject<Block> RED_TITANIUM_ORE = REGISTRY.register("red_titanium_ore", () -> new Red_TitaniumOreBlock());
	public static final RegistryObject<Block> RED_TITANIUM_BLOCK = REGISTRY.register("red_titanium_block", () -> new Red_TitaniumBlockBlock());
	public static final RegistryObject<Block> UNSEEN_ORE = REGISTRY.register("unseen_ore", () -> new UnseenOreBlock());
	public static final RegistryObject<Block> UNSEEN_BLOCK = REGISTRY.register("unseen_block", () -> new UnseenBlockBlock());
	public static final RegistryObject<Block> NATURERIUM_BLOCK = REGISTRY.register("naturerium_block", () -> new NatureriumBlockBlock());
	public static final RegistryObject<Block> COLD_DARK_BRICKS = REGISTRY.register("cold_dark_bricks", () -> new ColdDarkBricksBlock());
	public static final RegistryObject<Block> GRASS_BLOCK_OF_SHINY_REDLIGHT = REGISTRY.register("grass_block_of_shiny_redlight", () -> new GrassBlockOfShinyRedlightBlock());
	public static final RegistryObject<Block> DARK_GRASS = REGISTRY.register("dark_grass", () -> new DarkGrassBlock());
	public static final RegistryObject<Block> AMETHYST_GRASS_BLOCK = REGISTRY.register("amethyst_grass_block", () -> new AmethystGrassBlockBlock());
	public static final RegistryObject<Block> RED_OOZE = REGISTRY.register("red_ooze", () -> new RedOozeBlock());
	public static final RegistryObject<Block> CRYSTALLIZED_DARK_SAND = REGISTRY.register("crystallized_dark_sand", () -> new CrystallizedDarkSandBlock());
	public static final RegistryObject<Block> TEALIVE_LUMINOUS_GRASS_BLOCK = REGISTRY.register("tealive_luminous_grass_block", () -> new TealiveLuminousGrassBlockBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_LEAVES = REGISTRY.register("dark_crimson_leaves", () -> new Dark_crimsonLeavesBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_WOOD = REGISTRY.register("dark_crimson_wood", () -> new Dark_crimsonWoodBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_LOG = REGISTRY.register("dark_crimson_log", () -> new Dark_crimsonLogBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_PLANKS = REGISTRY.register("dark_crimson_planks", () -> new Dark_crimsonPlanksBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_STAIRS = REGISTRY.register("dark_crimson_stairs", () -> new Dark_crimsonStairsBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_SLAB = REGISTRY.register("dark_crimson_slab", () -> new Dark_crimsonSlabBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_TRAPDOOR = REGISTRY.register("dark_crimson_trapdoor", () -> new DarkCrimsonTrapdoorBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_DOOR = REGISTRY.register("dark_crimson_door", () -> new DarkCrimsonDoorBlock());
	public static final RegistryObject<Block> GRIZZLY_WOOD = REGISTRY.register("grizzly_wood", () -> new GrizzlyWoodBlock());
	public static final RegistryObject<Block> GRIZZLY_LOG = REGISTRY.register("grizzly_log", () -> new GrizzlyLogBlock());
	public static final RegistryObject<Block> GRIZZLY_PLANKS = REGISTRY.register("grizzly_planks", () -> new GrizzlyPlanksBlock());
	public static final RegistryObject<Block> GRIZZLY_LEAVES = REGISTRY.register("grizzly_leaves", () -> new GrizzlyLeavesBlock());
	public static final RegistryObject<Block> GRIZZLY_STAIRS = REGISTRY.register("grizzly_stairs", () -> new GrizzlyStairsBlock());
	public static final RegistryObject<Block> GRIZZLY_SLAB = REGISTRY.register("grizzly_slab", () -> new GrizzlySlabBlock());
	public static final RegistryObject<Block> GRIZZLY_TRAPDOOR = REGISTRY.register("grizzly_trapdoor", () -> new GrizzlyTrapdoorBlock());
	public static final RegistryObject<Block> GRIZZLY_DOOR = REGISTRY.register("grizzly_door", () -> new GrizzlyDoorBlock());
	public static final RegistryObject<Block> GRIZZLY_LIGHT_BLOCK = REGISTRY.register("grizzly_light_block", () -> new GrizzlyLightBlockBlock());
	public static final RegistryObject<Block> AMETHYST_LEAVES = REGISTRY.register("amethyst_leaves", () -> new AmethystLeavesBlock());
	public static final RegistryObject<Block> AMETHYST_WOOD = REGISTRY.register("amethyst_wood", () -> new AmethystWoodBlock());
	public static final RegistryObject<Block> AMETHYST_LOG = REGISTRY.register("amethyst_log", () -> new AmethystLogBlock());
	public static final RegistryObject<Block> AMETHYST_PLANKS = REGISTRY.register("amethyst_planks", () -> new AmethystPlanksBlock());
	public static final RegistryObject<Block> AMETHYST_STAIRS = REGISTRY.register("amethyst_stairs", () -> new AmethystStairsBlock());
	public static final RegistryObject<Block> AMETHYST_SLAB = REGISTRY.register("amethyst_slab", () -> new AmethystSlabBlock());
	public static final RegistryObject<Block> AMETHYST_TRAPDOOR = REGISTRY.register("amethyst_trapdoor", () -> new AmethystTrapdoorBlock());
	public static final RegistryObject<Block> AMETHYST_DOOR = REGISTRY.register("amethyst_door", () -> new AmethystDoorBlock());
	public static final RegistryObject<Block> TEALIVY_LEAVES = REGISTRY.register("tealivy_leaves", () -> new TealivyLeavesBlock());
	public static final RegistryObject<Block> TEALIVY_WOOD = REGISTRY.register("tealivy_wood", () -> new TealivyWoodBlock());
	public static final RegistryObject<Block> TEALIVY_LOG = REGISTRY.register("tealivy_log", () -> new TealivyLogBlock());
	public static final RegistryObject<Block> TEALIVY_PLANKS = REGISTRY.register("tealivy_planks", () -> new TealivyPlanksBlock());
	public static final RegistryObject<Block> TEALIVY_STAIRS = REGISTRY.register("tealivy_stairs", () -> new TealivyStairsBlock());
	public static final RegistryObject<Block> TEALIVY_SLAB = REGISTRY.register("tealivy_slab", () -> new TealivySlabBlock());
	public static final RegistryObject<Block> TEALIVY_TRAPDOOR = REGISTRY.register("tealivy_trapdoor", () -> new TealivyTrapdoorBlock());
	public static final RegistryObject<Block> TEALIVY_DOOR = REGISTRY.register("tealivy_door", () -> new TealivyDoorBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_LEAVES = REGISTRY.register("greenish_burly_wood_leaves", () -> new Greenish_BurlyWoodLeavesBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_WOOD = REGISTRY.register("greenish_burly_wood_wood", () -> new Greenish_BurlyWoodWoodBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_LOG = REGISTRY.register("greenish_burly_wood_log", () -> new Greenish_BurlyWoodLogBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_PLANKS = REGISTRY.register("greenish_burly_wood_planks", () -> new Greenish_BurlyWoodPlanksBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_STAIRS = REGISTRY.register("greenish_burly_wood_stairs", () -> new Greenish_BurlyWoodStairsBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_SLAB = REGISTRY.register("greenish_burly_wood_slab", () -> new Greenish_BurlyWoodSlabBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_TRAPDOOR = REGISTRY.register("greenish_burly_wood_trapdoor", () -> new GreenishBurlyWoodTrapdoorBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_DOOR = REGISTRY.register("greenish_burly_wood_door", () -> new GreenishBurlyWoodDoorBlock());
	public static final RegistryObject<Block> TANZASHROOM_LIGHT = REGISTRY.register("tanzashroom_light", () -> new TanzashroomLightBlock());
	public static final RegistryObject<Block> TANZANITE_BLOCK = REGISTRY.register("tanzanite_block", () -> new TanzaniteBlockBlock());
	public static final RegistryObject<Block> TANZANITE_BLOCK_BUDDING = REGISTRY.register("tanzanite_block_budding", () -> new TanzaniteBlockBuddingBlock());
	public static final RegistryObject<Block> TANZANITE_CLUSTER = REGISTRY.register("tanzanite_cluster", () -> new TanzaniteClusterBlock());
	public static final RegistryObject<Block> TANZANITE_BRICKS = REGISTRY.register("tanzanite_bricks", () -> new TanzaniteBricksBlock());
	public static final RegistryObject<Block> TANZANITE_BRICKS_STAIRS = REGISTRY.register("tanzanite_bricks_stairs", () -> new TanzaniteBricksStairsBlock());
	public static final RegistryObject<Block> TANZANITE_BRICKS_SLAB = REGISTRY.register("tanzanite_bricks_slab", () -> new TanzaniteBricksSlabBlock());
	public static final RegistryObject<Block> TANZANITE_BRICKS_WALL = REGISTRY.register("tanzanite_bricks_wall", () -> new TanzaniteBricksWallBlock());
	public static final RegistryObject<Block> DAKNESS_ANCIENT_BRICKS = REGISTRY.register("dakness_ancient_bricks", () -> new DaknessAncientBricksBlock());
	public static final RegistryObject<Block> DAKNESS_ANCIENT_BRICKS_STAIRS = REGISTRY.register("dakness_ancient_bricks_stairs", () -> new DaknessAncientBricksStairsBlock());
	public static final RegistryObject<Block> DAKNESS_ANCIENT_BRICKS_SLAB = REGISTRY.register("dakness_ancient_bricks_slab", () -> new DaknessAncientBricksSlabBlock());
	public static final RegistryObject<Block> DAKNESS_ANCIENT_BRICKS_WALL = REGISTRY.register("dakness_ancient_bricks_wall", () -> new DaknessAncientBricksWallBlock());
	public static final RegistryObject<Block> REDDEEPSLATEBRICKS = REGISTRY.register("reddeepslatebricks", () -> new ReddeepslatebricksBlock());
	public static final RegistryObject<Block> REDDEEPSLATEBRICKSSLAB = REGISTRY.register("reddeepslatebricksslab", () -> new ReddeepslatebricksslabBlock());
	public static final RegistryObject<Block> REDDEEPSLATEBRICKSSTAIRS = REGISTRY.register("reddeepslatebricksstairs", () -> new ReddeepslatebricksstairsBlock());
	public static final RegistryObject<Block> REDDEEPSLATEBRICKS_FENCE = REGISTRY.register("reddeepslatebricks_fence", () -> new ReddeepslatebricksFenceBlock());
	public static final RegistryObject<Block> CHLORITE_SLATE_STONE = REGISTRY.register("chlorite_slate_stone", () -> new ChloriteSlateStoneBlock());
	public static final RegistryObject<Block> CHLORITE_SLATE_STONE_BRICKS = REGISTRY.register("chlorite_slate_stone_bricks", () -> new ChloriteSlateStoneBricksBlock());
	public static final RegistryObject<Block> CHLORITE_SLATE_STONE_BRICKS_STAIRS = REGISTRY.register("chlorite_slate_stone_bricks_stairs", () -> new ChloriteSlateStoneBricksStairsBlock());
	public static final RegistryObject<Block> CHLORITE_SLATE_STONE_BRICKS_SLAB = REGISTRY.register("chlorite_slate_stone_bricks_slab", () -> new ChloriteSlateStoneBricksSlabBlock());
	public static final RegistryObject<Block> CHLORITE_SLATE_STONE_BRICKS_WALL = REGISTRY.register("chlorite_slate_stone_bricks_wall", () -> new ChloriteSlateStoneBricksWallBlock());
	public static final RegistryObject<Block> REINFORCED_POLISHED_BLACKSTONE_BRICKS = REGISTRY.register("reinforced_polished_blackstone_bricks", () -> new ReinforcedPolishedBlackstoneBricksBlock());
	public static final RegistryObject<Block> REINFORCED_POLISHED_BLACKSTONE_BRICKS_SLAB = REGISTRY.register("reinforced_polished_blackstone_bricks_slab", () -> new ReinforcedPolishedBlackstoneBricksSlabBlock());
	public static final RegistryObject<Block> ANCIENT_TRANSIENT_BLOCK_CLOSE = REGISTRY.register("ancient_transient_block_close", () -> new AncientTransientBlockCloseBlock());
	public static final RegistryObject<Block> REINFORCED_RED_ANIENT_BRICKS = REGISTRY.register("reinforced_red_anient_bricks", () -> new ReinforcedRedAnientBricksBlock());
	public static final RegistryObject<Block> BEACON_RUNE = REGISTRY.register("beacon_rune", () -> new BeaconRuneBlock());
	public static final RegistryObject<Block> BEACON_OF_WEAPONS = REGISTRY.register("beacon_of_weapons", () -> new BeaconOfWeaponsBlock());
	public static final RegistryObject<Block> DRIPSTONE_OF_AMETHYST_OVERGROWTH = REGISTRY.register("dripstone_of_amethyst_overgrowth", () -> new DripstoneOfAmethystOvergrowthBlock());
	public static final RegistryObject<Block> DEEP_WATER_ANFELTSIA = REGISTRY.register("deep_water_anfeltsia", () -> new DeepWaterAnfeltsiaBlock());
	public static final RegistryObject<Block> GOLDENCHEST = REGISTRY.register("goldenchest", () -> new GoldenchestBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_FENCE_GATE = REGISTRY.register("dark_crimson_fence_gate", () -> new Dark_crimsonFenceGateBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_PRESSURE_PLATE = REGISTRY.register("dark_crimson_pressure_plate", () -> new Dark_crimsonPressurePlateBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_BUTTON = REGISTRY.register("dark_crimson_button", () -> new Dark_crimsonButtonBlock());
	public static final RegistryObject<Block> GRIZZLY_FENCE_GATE = REGISTRY.register("grizzly_fence_gate", () -> new GrizzlyFenceGateBlock());
	public static final RegistryObject<Block> GRIZZLY_PRESSURE_PLATE = REGISTRY.register("grizzly_pressure_plate", () -> new GrizzlyPressurePlateBlock());
	public static final RegistryObject<Block> GRIZZLY_BUTTON = REGISTRY.register("grizzly_button", () -> new GrizzlyButtonBlock());
	public static final RegistryObject<Block> AMETHYST_FENCE_GATE = REGISTRY.register("amethyst_fence_gate", () -> new AmethystFenceGateBlock());
	public static final RegistryObject<Block> AMETHYST_PRESSURE_PLATE = REGISTRY.register("amethyst_pressure_plate", () -> new AmethystPressurePlateBlock());
	public static final RegistryObject<Block> AMETHYST_BUTTON = REGISTRY.register("amethyst_button", () -> new AmethystButtonBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_FENCE_GATE = REGISTRY.register("greenish_burly_wood_fence_gate", () -> new Greenish_BurlyWoodFenceGateBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_PRESSURE_PLATE = REGISTRY.register("greenish_burly_wood_pressure_plate", () -> new Greenish_BurlyWoodPressurePlateBlock());
	public static final RegistryObject<Block> GREENISH_BURLY_WOOD_BUTTON = REGISTRY.register("greenish_burly_wood_button", () -> new Greenish_BurlyWoodButtonBlock());
	public static final RegistryObject<Block> TEALIVY_FENCE_GATE = REGISTRY.register("tealivy_fence_gate", () -> new TealivyFenceGateBlock());
	public static final RegistryObject<Block> TEALIVY_PRESSURE_PLATE = REGISTRY.register("tealivy_pressure_plate", () -> new TealivyPressurePlateBlock());
	public static final RegistryObject<Block> TEALIVY_BUTTON = REGISTRY.register("tealivy_button", () -> new TealivyButtonBlock());
	public static final RegistryObject<Block> BLAZER_SUMMON_BLOCK = REGISTRY.register("blazer_summon_block", () -> new BlazerSummonBlockBlock());
	public static final RegistryObject<Block> DARK_CRIMSON_BLOOMING_VINE = REGISTRY.register("dark_crimson_blooming_vine", () -> new DarkCrimsonBloomingVineBlock());
	public static final RegistryObject<Block> THE_WITHER_KNIGHT_BLOCK = REGISTRY.register("the_wither_knight_block", () -> new TheWitherKnightBlockBlock());
	public static final RegistryObject<Block> MISTERYFLOWER_WITH_FEW_BERRIES = REGISTRY.register("misteryflower_with_few_berries", () -> new MisteryflowerWithFewBerriesBlock());
	public static final RegistryObject<Block> MISTERYFLOWER_BERRIES = REGISTRY.register("misteryflower_berries", () -> new MisteryflowerBerriesBlock());
	public static final RegistryObject<Block> ANCIENT_TRANSIENT_BLOCK_OPEN = REGISTRY.register("ancient_transient_block_open", () -> new AncientTransientBlockOpenBlock());
	public static final RegistryObject<Block> UNDEAD_WARRIOR_OF_THE_CHIMERIC_DARKNESS = REGISTRY.register("undead_warrior_of_the_chimeric_darkness", () -> new UndeadWarriorOfTheChimericDarknessBlock());
	public static final RegistryObject<Block> TOTEMOF_GUDDY_BLAZE = REGISTRY.register("totemof_guddy_blaze", () -> new TotemofGuddyBlazeBlock());

	@Mod.EventBusSubscriber(bus = Mod.EventBusSubscriber.Bus.MOD, value = Dist.CLIENT)
	public static class ClientSideHandler {
		@SubscribeEvent
		public static void blockColorLoad(RegisterColorHandlersEvent.Block event) {
			AmethystGrassBlock.blockColorLoad(event);
			TanzashroomBlock.blockColorLoad(event);
			TanzashroomStemBlock.blockColorLoad(event);
			CrystallizedDarkSandBlock.blockColorLoad(event);
			DeepWaterAnfeltsiaBlock.blockColorLoad(event);
		}

		@SubscribeEvent
		public static void itemColorLoad(RegisterColorHandlersEvent.Item event) {
			TanzashroomBlock.itemColorLoad(event);
			TanzashroomStemBlock.itemColorLoad(event);
		}
	}
}
